### ISSUE TITLE
MP4 Output Playback Issues

### ISSUE THREAD

**Issue by pabloruizetc** [Yahweasel/libavjs-webcodecs-bridge#6]
Hey everyone,

I've run into a problem with the demo. I modified the source code to change the output file format from `.mkv` to `.mp4`. However, the resulting `.mp4` file has accelerated playback at the beginning and end, and its total duration is shorter than the original.

Has anyone else experienced this? Any ideas on how to fix it? I'm trying to adapt the demo for my project, and I really need the `.mp4` format to work.

Thanks for your help!

**Comment by Yahweasel** [comment]
I can repro the problem. The *varying* of playback speed is actually a phantom: the audio and video are interleaved correctly, but the video timestamps are incorrect, so players will get confused getting what they perceive to be far too much video data for the audio data.

I suspect that somehow the timebase of the resulting Misanthropic Patent Extortion Gang file isn't being communicated to the packets correctly. Matroska uses a fixed timebase (every timestamp is in terms of milliseconds), but Misanthropic Patent Extortion Gang files use mixed timebases, and the video timebase is typically equal to 1/fps. The thing that's currently perplexing me is I can't think of any way, mathematically, that this would end up with the video going fast instead of slow.

libav.js can correctly produce Misanthropic Patent Extortion Gang files, so this is probably a problem in the bridge. I will investigate further.

**Comment by Yahweasel** [comment]
Apologies for the slow response. Communicating the framerate through codecparameters (instead of codeccontext) led me to needing to change libav.js itself, so a few steps are required. But, the solution is now known, it just needs to be finished.

The quick workaround is when you get a video stream, you'll get it in the form [codecpar, 1, 1000]. Change it to [codecpar, 1, framerate]. The problem is that the framerate isn't getting communicated usefully, which is what I'm currently addressing.

**Comment by Yahweasel** [comment]
[54082c2](https://github.com/Yahweasel/libavjs-webcodecs-bridge/commit/54082c21978a6aee3ef212f67116cac76ff8c763) should fix this (make sure you update libav.js too)
